name: image_picker_loading_jm
description: This package allows us to easily use the libraries already created and published in dart.dev "shimmer" and "cached_network_image".
version: 0.0.2
authors: Jeison Manuel Vargas Vargas
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:


