name: image_picker_loading_jm
version: 0.0.9
description: This package allows us to easily use the libraries already created and published in dart.dev "shimmer" and "cached_network_image".
homepage: https://github.com/JeisonManuelVargas/image_picker_loading_jm

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:


