name: build main branch

on:
  pull_request:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  deploy_to_pub_get:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: dart:stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Pub credentials
        run: echo '//pub.dartlang.org:443/          *' > ~/.pub-cache/credentials
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUBDEV_TOKEN }}

      - name: Install dependencies
        run: flutter pub get 
        
      - name: Publish
        run: flutter pub publish --force

