name: build main branch

on:
  pull_request:
    branches: [ main ]
    type: [ opened, reopened ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'


concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  deploy_to_pub_get:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'

      - name: Install dependencies
        run: flutter pub get
      # Here you can insert custom steps you need
      # - run: dart tool/generate-code.dart
      - name: Publish package to pub.dev
        run: dart pub publish --dry-run
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUBDEV_TOKEN }}

