name: build main branch

on:
  pull_request:
    branches: [ main ]
    type: [ opened, reopened ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  deploy_to_pub_get:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: nikosportolos/dart_package@v0.2.1
        with:
          coverage: true
          codecov: true
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          publish: true
          pubdev_token: ${{ secrets.PUBDEV_TOKEN }}

