name: build develop branch

on:
  pull_request:
    branches: [ main ]
    type: [ opened, reopened ]

jobs:
  build_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: implemented test
        run: flutter test
#############################################
# second jobs. deploy to pub.get
#############################################

  deploy_to_pub_get:
    runs-on: ubuntu-latest

    needs: build_develop

    if: ${{ success() }}

    steps:
      - name: Publish
        run: dart pub publish --force

