# .github/workflows/publish.yml
# This workflow runs when publishing a Dart package on pub.dev.
name: Publish Workflow

on:
  pull_request:
    branches: [ develop ]
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        working-directory: .
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'

      - name: Install dependencies
        run: flutter pub get

      - uses: actions/checkout@v4
      - uses: nikosportolos/dart_package@v0.2.1
        with:
          coverage: true
          codecov: true
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          publish: true
          pubdev_token: ${{ secrets.PUBDEV_TOKEN }}