name: build main branch

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy_to_pub_get:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'

      - name: Get dependencies
        run: flutter pub get

      - name: Create pub-cache directory
        run: mkdir -p ~/.pub-cache/

      - name: Set up Pub credentials
        run: echo '//pub.dartlang.org:443/          *' > ~/.pub-cache/credentials
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}

      - name: Get dependencies
        run: flutter pub get

      - name: Publish package to Pub.dev
        run: flutter pub publish -f

